# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  release:
    types:
      - created
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Fetch Release
        id: fetch_release
        uses: gregziegan/fetch-latest-release@v2.0.0

      # Runs a single command using the runners shell
      - name: Update Release XML
        run: |
          $bumpedVersion = '${{ steps.fetch_release.outputs.tag_name }}'
          $file = Get-Item .\UpdateInfo.xml
          [xml]$updateInfoXml = Get-Content $file
          $updateInfoXml.item.version = $bumpedversion
          $updateInfoXml.item.url = "https://github.com/Dima-Kal/BuzzrAutoRelease/releases/download/$($bumpedversion)/BuzzrAuto.zip"
          $updateInfoXml.Save($file.FullName)
          
      - name: Update Release Notes File
        run: |
          $ReleaseNotes = '${{ steps.fetch_release.outputs.body }}'
          $newLine = "`r`n"
          Set-Content -Path .\ReleaseNotes.txt -Value $ReleaseNotes.Replace('-', ($newLine+'-')).Trim()
          
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7.5.0 # You can change this to use a specific version.
        with:
          message: 'Added release ${{ steps.fetch_release.outputs.tag_name }}'  
          pull: 'NO-PULL'
